name = "benaka-rentals-app"
main = "backend/src/index.ts"
compatibility_date = "2024-04-04"

[assets]
directory = "frontend/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "benaka"
database_id = "34f2cd27-94f6-4eb7-be8b-38c080a6d59d" 
