name = "benaka-rentals-app"
main = "backend/src/index.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "frontend/dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "benaka"
database_id = "34f2cd27-94f6-4eb7-be8b-38c080a6d59d" 
